Added sounds
zoompower/Hivemind pull request #16
Opened 2020-05-19 13:45 UTC by MMCQ33

Added sounds and made them scaleable with volume. Added exclamationMark when ant finds resource

2020-05-19 14:07 UTC, ErikLouwerse requested changes

2020-05-19 14:07 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Minds/Gathering.cs
> +    private GameObject excla;
Keep this is the function pls, no need for the whole class to know about it

2020-05-19 14:07 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/TestScript.cs
> +            for (int x = 0; x < 20; x++)
pls no

2020-05-19 14:07 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/TestScript.cs
> +using System.Security.Cryptography.X509Certificates;
????

2020-05-19 14:07 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Minds/Gathering.cs
> +    private void FoundResource()
Just put everything in the Discover function and start the coroutine where this function is currently called

2020-05-20 08:16 UTC, ErikLouwerse requested changes

2020-05-20 08:16 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Minds/Gathering.cs
> +                        if (IsScout && target != null)
make double if into a single one

2020-05-20 08:16 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Minds/Gathering.cs
> +         excla.transform.localScale *= 3;
Spacing

2020-05-20 08:16 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/ResourceNode.cs
> +            if (this.resourceType == ResourceType.Crystal)
useless this.

2020-05-20 08:16 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Ant.cs
> +    private float audioVolume = 1f;
Why not just change the audioSrc.volume direly, this field seems redundant

2020-05-20 08:16 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/ResourceNode.cs
> +        if (this.resourceType == ResourceType.Crystal)
this.

2020-05-20 08:16 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/ResourceNode.cs
> +    private float audioVolume = 1;
Seems redundant, see other comment

2020-05-20 08:36 UTC, ErikLouwerse requested changes

2020-05-20 08:36 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Ant.cs
> +    private float audioVolume = 1f;
REMOVE PLS

2020-05-20 08:53 UTC, ErikLouwerse requested changes

2020-05-20 08:53 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Ant.cs
> +        audioSrc.volume *=  0.05f;
this needs to be in the if, otherwise the audio will just decrease

2020-05-20 09:00 UTC, ErikLouwerse approved these changes

2020-05-20 09:25 UTC, zoompower approved these changes

2020-05-20 09:27 UTC, merged