#39 map switching
zoompower/Hivemind pull request #22
Opened 2020-05-28 08:49 UTC by MMCQ33

2020-05-28 09:19 UTC, ErikLouwerse requested changes
change vars to actual types pls

2020-05-28 09:39 UTC, ErikLouwerse approved these changes

2020-05-29 07:46 UTC, jetenergy commented on Hivemind/Assets/Scripts/Ui/UiController.cs
> +    [SerializeField] private GameObject mainCamera;
Deze kan je vinden aangezien er maar 1 maincamera object per scene aanwezig is, heb je ook minder problemen met een nieuwe map aanmaken waar je dit handmatig moet invullen

2020-05-29 07:47 UTC, jetenergy commented on Hivemind/Assets/Scripts/Ui/UiController.cs
> +    [SerializeField] private GameObject mainCamera;
dit doe je namelijk ook met minimaps

2020-05-29 07:59 UTC, jetenergy approved these changes

2020-05-29 09:45 UTC, jetenergy approved these changes

2020-05-29 09:45 UTC, merged