#40 testing
zoompower/Hivemind pull request #26
Opened 2020-06-04 13:06 UTC by MMCQ33

Added More testing

2020-06-05 14:22 UTC, ErikLouwerse requested changes

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/BaseBuildingTestScene.unity
> +%YAML 1.1
Please put this in the scenes folder

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Scenes/BaseBuildingTestScene 1.meta
> +fileFormatVersion: 2
What meta file is this for?

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Ant.cs
> +    public List<IMind> GetMinds()
It's already public.
Please remove or make public set function and private the variable

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/MindGroup.cs
> +    public List<IMind> Minds { get; set; }
pls remove getset as it is useless

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Minds/Gathering.cs
> +            if (state == State.Idle)
just make double if

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/Minds/Gathering.cs
> +
WHITESPACE

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Tests/PlayModeTests/BaseBuildingTest.cs
> +        private UnitController unitControl;
Useless

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Tests/PlayModeTests/BaseBuildingTest.cs
> +            yield return new WaitForSeconds(1f);
```suggestion
            AsyncOperation asyncLoadLevel = SceneManager.LoadSceneAsync("BaseBuildingTestScene", LoadSceneMode.Single);
            while (!asyncLoadLevel.isDone)
            {
                Debug.Log("Loading the Scene");
                yield return null;
            }
```

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Tests/PlayModeTests/GatherResourceTest.cs
> +
WHITESPACE

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Tests/PlayModeTests/GatherResourceTest.cs
> +            yield return new WaitForSeconds(1f);
```suggestion
            AsyncOperation asyncLoadLevel = SceneManager.LoadSceneAsync("TestScene", LoadSceneMode.Single);
            while (!asyncLoadLevel.isDone)
            {
                Debug.Log("Loading the Scene");
                yield return null;
            }
```

2020-06-05 14:22 UTC, ErikLouwerse commented on Hivemind/Assets/Tests/PlayModeTests/MindBuilderTest.cs
> +﻿using NUnit.Framework;
too much bad white space to comment

2020-06-09 08:16 UTC, zoompower approved these changes

2020-06-10 08:46 UTC, ErikLouwerse approved these changes

2020-06-10 11:35 UTC, merged