#41 teams
zoompower/Hivemind pull request #29
Opened 2020-06-10 09:40 UTC by jetenergy

Added teams stuffs, please look at [trello](https://trello.com/c/GOjSLNHx/57-41-teams) to see what has been done

2020-06-10 12:19 UTC, zoompower approved these changes

2020-06-11 08:31 UTC, ErikLouwerse requested changes
Resources that are discovered don't become visible

2020-06-11 08:42 UTC, ErikLouwerse requested changes

2020-06-11 08:42 UTC, ErikLouwerse commented on Hivemind/Assets/Scripts/ResourceNode.cs
> +    {
This breaks saving and loading pls remove

2020-06-11 09:02 UTC, ErikLouwerse approved these changes

2020-06-11 09:44 UTC, MMCQ33 approved these changes

2020-06-11 09:44 UTC, MMCQ33 commented on Hivemind/Assets/Scripts/Data/TeamMindGroup.cs
> +    public class TeamMindGroup
pls name this teammindgroupdata

2020-06-11 09:44 UTC, merged